baseurl = "https://33togetrich.netlify.app"
title = "33togetrich"
theme = "hugo-coder"

[params]
  plantuml = true

# PlantUML configuration
[params.plantuml]
  svg_image_url = "https://www.plantuml.com/plantuml/svg/"
  svg = true
